//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demo3Entities1 : DbContext
    {
        public demo3Entities1()
            : base("name=demo3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MaterialType_> MaterialType_ { get; set; }
        public virtual DbSet<Partners_> Partners_ { get; set; }
        public virtual DbSet<Product_> Product_ { get; set; }
        public virtual DbSet<ProductMaterialType_> ProductMaterialType_ { get; set; }
        public virtual DbSet<ProductType_> ProductType_ { get; set; }
        public virtual DbSet<Sale_> Sale_ { get; set; }
        public virtual DbSet<TypePartner_> TypePartner_ { get; set; }
    }
}
