//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaterialType_
    {
        public int IDProductMaterialType { get; set; }
        public int ProductArticle { get; set; }
        public Nullable<int> IDMaterialType { get; set; }
    
        public virtual MaterialType_ MaterialType_ { get; set; }
        public virtual Product_ Product_ { get; set; }
    }
}
