//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_
    {
        public int IDSale { get; set; }
        public Nullable<int> ProductArticle { get; set; }
        public Nullable<int> Partner { get; set; }
        public string CountProduct { get; set; }
        public string SaleDate { get; set; }
    
        public virtual Partners_ Partners_ { get; set; }
        public virtual Product_ Product_ { get; set; }
    }
}
